POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json

{
    "username": "Alexa",
    "email": "alexa@example.com",
    "password": "1234"
}

###

# Send Request
GET http://127.0.0.1:8000/api/auth/user
Authorization: Token 24cab3a9f84e3da177d3bff76f1a6457aff0b80030d036689ce629bfec1708da

###

# Send Request
POST http://127.0.0.1:8000/api/auth/logout
Authorization: Token 24cab3a9f84e3da177d3bff76f1a6457aff0b80030d036689ce629bfec1708da

###

# Send Request
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
    "username": "Mary",
    "password": "1234"
}

###

# Send Request
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
    "username": "Alexa",
    "password": "1234"
}

###