# Generated by Django 3.0.5 on 2020-05-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('hello_message', models.CharField(blank=True, max_length=200)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
