# Generated by Django 3.0.5 on 2020-05-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20200503_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
