# Generated by Django 3.0.5 on 2020-05-19 01:56

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=candidates.models.get_image_path),
        ),
    ]
