# Generated by Django 3.0.5 on 2020-05-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
