# Generated by Django 3.0.5 on 2020-05-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_description', models.FileField(blank=True, default=None, null=True, upload_to='./media/job_description')),
                ('keywords', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='candidates.Keywords')),
            ],
        ),
    ]
