export const GET_CANDIDATES = 'GET_CANDIDATES';
export const GET_CANDIDATE = 'GET_CANDIDATE';
export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const DELETE_CANDIDATE = 'DELETE_CANDIDATE';
export const EDIT_CANDIDATE = 'EDIT_CANDIDATE';
export const GET_CANDIDATE_SCORE = 'GET_CANDIDATE_SCORE';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_KEYWORDS = 'GET_KEYWORDS';
export const GET_KEYWORD = 'GET_KEYWORD';
export const ADD_KEYWORD = 'ADD_KEYWORD';
export const DELETE_KEYWORD = 'DELETE_KEYWORD';
export const EDIT_KEYWORD = 'EDIT_KEYWORD';

export const GET_JOBS = 'GET_JOBS';
export const ADD_JOB = 'ADD_JOB';